### ISSUE TITLE
hotp.generate parameter not allow UInt64

### ISSUE THREAD

**Issue by RaviMalviya** [lachlanbell/SwiftOTP#2]
Example - hotp.generate(counter: 42)
counter allow only Int, it should also allows UInt64, please make a new function that allows UInt64 as a parameter.

**Comment by lachlanbell** [comment]
True, I'll change it to an 8-byte `UInt64` in accordance with [RFC 4226](https://tools.ietf.org/html/rfc4226#section-5.1), and as that's what is already used internally.

**Comment by RaviMalviya** [comment]
Please let me know in the same reply chain.

**Comment by lachlanbell** [comment]
Swift 4.1 is source compatible with 4.0
