### ISSUE TITLE
Possible Issues on Swift 5.2 (Xcode 11.4.1)

### ISSUE THREAD

**Issue by vialyx** [lachlanbell/SwiftOTP#20]
https://github.com/lachlanbell/SwiftOTP/blob/4c919ab7f007bed0c97c97a640260ac1b31f8a1a/SwiftOTP/Base32/Base32.swift#L53

I guess you can possible have same issues as occurred into SwiftyRSA
https://github.com/TakeScoop/SwiftyRSA/issues/183

**Comment by lachlanbell** [comment]
Thanks for letting me know - from what I can see the issue there is with interacting with the Apple crypto APIs, which this library doesn't use.

**Comment by vialyx** [comment]
@lachlanbell 
Base32 is hosted into project. Not as pod dependency.
According that I have been prepared fork with fixes.
https://github.com/lachlanbell/SwiftOTP/pull/21
