### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by Tutorialwork** [lachlanbell/SwiftOTP#31]
When I am trying to build a watchOS app using this library everything is working fine but after the upload to the App Store I get the following error as email.

`TMS-90562: Invalid Bundle - Bitcode failed to compile for your watchOS binary because it includes assembly source code or inline assembly. To resolve this issue, rewrite the corresponding code in a higher-level language such as Objective-C or Swift and redeliver your app.`

Is it possible to add bitcode support? For iOS I can disable the bitcode support, but for watchOS is it required.

**Comment by lachlanbell** [comment]
Hi, sorry I missed this issue! Since this was flagged, Apple has deprecated bitcode and no longer requires it for watchOS.
