### ISSUE TITLE
Undefined Symbol Error

### ISSUE THREAD

**Issue by rainrain1230** [lachlanbell/SwiftOTP#36]
When I add the package to my project, there are three undefined symbol errors:

Undefined symbol: _$s8SwiftOTP18base32DecodeToDatay10Foundation0F0VSgSSF

Undefined symbol: _$s8SwiftOTP4TOTPV6secret6digits12timeInterval9algorithmACSg10Foundation4DataV_S2iAA12OTPAlgorithmOtcfC

Undefined symbol: _$s8SwiftOTP4TOTPV8generate4timeSSSg10Foundation4DateV_tF

Would you know how can I resolve this?

**Comment by lachlanbell** [comment]
Hi mate, I can't reproduce this on a fresh project—would you mind clearing your Xcode derived data folder and trying again?

**Comment by lachlanbell** [comment]
Closing this—please reopen if you're still seeing this issue 🙏
