### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by dbarden** [lachlanbell/SwiftOTP#38]
Hey,

Would it be possible to create a new patch release for this project? We have SwiftOTP as a dependency in a project and would like to link it via SPM as a dynamic library.

Today we need to point it to `master` but we would like to be able to point to a tag :) 

Let me know if there's anything I can help with.

Thanks in advance.

**Comment by lachlanbell** [comment]
Hi @dbarden — [tag 3.0.1](https://github.com/lachlanbell/SwiftOTP/releases/tag/3.0.1) should be good to go. Let me know if you hit any trouble 🙂.
